name: Build Nexa Music APK

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Java 17
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: 'platform-tools platforms;android-35 build-tools;35.0.0'

      - name: Set up Gradle 8.9
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.9'

      - name: Extract Nexa Music
        run: |
          rm -rf projeto
          mkdir -p projeto
          unzip -o NexaMusic_v1.zip -d projeto
          echo "Arquivos encontrados:"
          ls -la projeto/NexaMusic_v1

      - name: Build Nexa Music APK
        working-directory: projeto/NexaMusic_v1
        run: |
          gradle :app:assembleDebug --no-daemon --stacktrace

      - name: Check generated APK
        run: |
          ls -lah projeto/NexaMusic_v1/app/build/outputs/apk/debug/

      - name: Upload Nexa Music APK
        uses: actions/upload-artifact@v4
        with:
          name: Nexa-Music-v1-APK
          path: projeto/NexaMusic_v1/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
